
name: Static Analysis
on:
  workflow_call:

jobs:
  static_analysis:
      name: Secrets Scan
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: 🔐 GitLeaks Secrets Scan
          run: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_x64.tar.gz | tar -xz
            ./gitleaks detect --source=. \
            --report-format=json \
            --report-path=gitleaks.json \
            --redact \
            --exit-code=0

        - name: 📦 Upload GitLeaks Report
          uses: actions/upload-artifact@v4
          with:
            name: gitleaks-report
            path: gitleaks-report.json