
name: Static Analysis
on:
  workflow_call:

jobs:
  static_analysis:
      name: 🧠 Static Analysis (Semgrep + Bandit)
      runs-on: ubuntu-latest
      steps:
        - name: 🔐 GitLeaks Scan
          uses: gitleaks/gitleaks-action@v2
          with:
            args: "--report-path=gitleaks-report.json --redact --verbose"

        - name: 📦 Upload GitLeaks Report
          uses: actions/upload-artifact@v4
          with:
            name: gitleaks-report
            path: gitleaks-report.json