name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  Secrets-Scan:
    uses: ./Gitleaks-secret.yml@main

  static-analysis:
    uses: ./static-analysis.yml@main

  trivy-scan:
    uses: ./.github/workflow/trivy-Container-scan.yml@main
    needs: static-analysis

  evaluate:
    uses: ./evaluate-results.yml@main
    needs: trivy-scan
