name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  
  Secrets-Scan:
    uses: kanedasec/DevSecOps/ci/Gitleaks-secret.yml@main

  static-analysis:
    uses: kanedasec/DevSecOps/.github/workflows/static-analysis.yml@main

  trivy-scan:
    uses: kanedasec/DevSecOps/.github/workflows/trivy-Container-scan.yml@main
    needs: static-analysis

  evaluate:
    uses: kanedasec/DevSecOps/.github/workflows/evaluate-results.yml@main
    needs: trivy-scan