
name: Full Security Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  static_analysis:
    name: 🧠 Static Analysis (Semgrep + Bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r app -f csv -o bandit_results.csv || true

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          output: semgrep_results.csv
          output-format: csv

      - name: Upload Static Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: |
            bandit_results.csv
            semgrep_results.csv

  container_and_sca_scan:
    name: 🐳 Container & Dependency Scan (Trivy)
    runs-on: ubuntu-latest
    needs: static_analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/

      - name: Build Docker image
        run: docker compose build flask-app

      - name: Scan Docker image
        run: |
          trivy image --format csv --output trivy_image.csv --severity HIGH,CRITICAL flask_app || true

      - name: Scan filesystem (SCA)
        run: |
          trivy fs --format csv --output trivy_fs.csv --scanners vuln,license,secret --severity HIGH,CRITICAL . || true

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy_image.csv
            trivy_fs.csv

  evaluate_results:
    name: ✅ Evaluate and Finalize
    runs-on: ubuntu-latest
    needs: [static_analysis, container_and_sca_scan]
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: trivy-reports
          path: reports

      - name: Check for HIGH or CRITICAL Vulnerabilities
        id: check_vulns
        run: |
          high_critical_count=$(grep -iE 'HIGH|CRITICAL' reports/*.csv | wc -l)
          echo "VULN_COUNT=$high_critical_count" >> $GITHUB_ENV

      - name: Fail if High/Critical vulnerabilities found
        if: env.VULN_COUNT != '0'
        run: |
          echo "❌ Please correct all High and Critical Vulnerabilities to move to PROD"
          exit 1

      - name: Success message
        if: env.VULN_COUNT == '0'
        run: echo "✅ Everything is in place to go to PROD"
