name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  static-analysis:
    uses: kanedasec/DevSecOps/.github/ci/static-analysis.yml

  trivy-scan:
    uses: kanedasec/DevSecOps/.github/ci/trivy-scan.yml
    needs: static-analysis

  evaluate:
    uses: kanedasec/DevSecOps/.github/ci/evaluate-results.yml
    needs: trivy-scan