name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  Secrets-Scan:
    uses: ./.github/workflows/gitleaks-secret.yml

  Static-Analysis:
    uses: ./.github/workflows/static-analysis.yml

  Container-Dependecy-Scan:
    uses: ./.github/workflows/trivy-Container-scan.yml
    needs: Static-Analysis

  Evaluate-Findings:
    uses: ./.github/workflows/evaluate-results.yml
    needs: Container-Dependecy-Scan
