name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  Secrets-Scan:
    uses: ./.github/workflows/gitleaks-secret.yml

  Static-Analysis:
    uses: ./.github/workflows/static-analysis.yml

  Container-Scan:
    uses: ./.github/workflows/trivy-Container-scan.yml
    needs: static-analysis

  Evaluate-Findings:
    uses: ./.github/workflows/evaluate-results.yml
    needs: trivy-scan
