name: Full Security Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write  # 👈 REQUIRED for uploading SARIF

jobs:
  Secrets-Scan:
    uses: ./.github/workflows/gitleaks-secret.yml

  Static-Analysis:
    uses: ./.github/workflows/static-analysis.yml

  Dependency-Scan:
    uses: ./.github/workflows/sca-scan.yml
    needs: Static-Analysis

  Evaluate-Findings:
    uses: ./.github/workflows/evaluate-results.yml
    needs: Dependency-Scan
