name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  static-analysis:
    uses: kanedasec/DevSecOps/.github/workflows/static-analysis.yml@main

  trivy-scan:
    uses: kanedasec/DevSecOps/.github/workflows/trivy-scan.yml@main
    needs: static-analysis

  evaluate:
    uses: kanedasec/DevSecOps/.github/workflows/evaluate-results.yml@main
    needs: trivy-scan