name: Full Security Pipeline

on:
  workflow_dispatch:

jobs:
  static-analysis:
    uses: ./ci/static-analysis.yml

  trivy-scan:
    uses: ./ci/trivy-scan.yml
    needs: static-analysis

  evaluate:
    uses: ./ci/evaluate-results.yml
    needs: trivy-scan